packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  protobufjs: true
  spawn-sync: false

confirmModulesPurge: false

minimumReleaseAgeExclude:
  - '@dabaoabc/ui-agent-agents@0.2.0'
  - '@dabaoabc/ui-agent-core@0.2.0'
  - '@dabaoabc/ui-agent-llms@0.2.0'
  - '@dabaoabc/ui-agent-sdk@0.2.0'
  - '@dabaoabc/ui-agent-shared@0.2.0'
